import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/sheets">Sheets</Link>
        </li>
        <li>
          <Link to="/sheetsauthoring">Sheetsauthoring</Link>
        </li>
        <li>
          <Link to="/sheetsone">SheetsOne</Link>
        </li>
        <li>
          <Link to="/sheetslibrary">SheetsLibrary</Link>
        </li>
        <li>
          <Link to="/frame">Frame</Link>
        </li>
        <li>
          <Link to="/sheetstwo">SheetsTwo</Link>
        </li>
        <li>
          <Link to="/sheetsthree">SheetsThree</Link>
        </li>
        <li>
          <Link to="/sheetsfour">SheetsFour</Link>
        </li>
        <li>
          <Link to="/sheetsfive">SheetsFive</Link>
        </li>
        <li>
          <Link to="/sheetssix">SheetsSix</Link>
        </li>
        <li>
          <Link to="/sheetsseven">SheetsSeven</Link>
        </li>
        <li>
          <Link to="/sheetslibraryone">SheetsLibraryOne</Link>
        </li>
        <li>
          <Link to="/sheetsauthoringone">SheetsauthoringOne</Link>
        </li>
        <li>
          <Link to="/sheetseight">SheetsEight</Link>
        </li>
        <li>
          <Link to="/sheetsnine">SheetsNine</Link>
        </li>
        <li>
          <Link to="/sheetsten">SheetsTen</Link>
        </li>
        <li>
          <Link to="/sheetseleven">SheetsEleven</Link>
        </li>
        <li>
          <Link to="/sheetstwelve">SheetsTwelve</Link>
        </li>
        <li>
          <Link to="/sheetsthirteen">SheetsThirteen</Link>
        </li>
        <li>
          <Link to="/sheetsfourteen">SheetsFourteen</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
